apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  namespaces: hdfs
  labels:
    type: zk
spec:
  containers:
  - name: zookeeper
    image: lllth94/k8s-zookeeper:latest
    ports:
    - containerPort: 2181
  - name: master01
    image: lllth94/k8s-zookeeper:latest
    ports:
    - containerPort: 2181
  - name: master02
    image: lllth94/k8s-zookeeper:latest
    ports:
    - containerPort: 2181
