apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  namespaces: hdfs
  labels:
    type: zk
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "10.97.203.143"
    hostnames:
    - "zookeeper"
    - "master01"
    - "master02"
  containers:
  - name: zookeeper
    image: lllth94/k8s-zookeeper:latest
    ports:
    - containerPort: 2181
  - name: master01
    image: lllth94/k8s-zookeeper:latest
    ports:
    - containerPort: 2181
  - name: master02
    image: lllth94/k8s-zookeeper:latest
    ports:
    - containerPort: 2181